ervices:
  app:
    image: bubai11/my-nodejs-project:latest
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - REDIS_ENABLED=false
      - NODE_ENV=production
    # 如果需要的话，可以加restart策略
    restart: unless-stopped